Repository malivinayak/Tic-Tac-Toe, pull requests merged in 2023-10, with the labels that each got.

#1 feat: game draw and the board reset feature
  assets/js/script.js
Labels: hacktoberfest-accepted

#2 style: bg update
  assets/css/index.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted

#5 doc: update the readme.md file with latest UI
  README.md
Labels: documentation, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#6 feat: Tic-Tac-Toe Rules added as pop-up
  assets/css/index.css
  assets/js/script.js
  index.html
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#10 refactor: add og property and icon
  assets/Images/image.png
  assets/Images/tic-tac-toe.png
  index.html
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#7 refactor: UI enhancement
  .gitignore
  assets/css/index.css
  assets/js/script.js
  index.html
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#17 feat: added fade out transition for rules pop-up
  assets/css/index.css
  assets/js/script.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#23 feat: undo and reset button
  assets/css/index.css
  assets/js/script.js
  index.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#24 feat: Added sound effect to win and draw state. (#20)
  assets/css/index.css
  assets/js/script.js
  assets/sound/gametie.mp3
  assets/sound/winsound.mp3
  index.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#25 refactor: update UI screenshot
  README.md
Labels: documentation, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#26 feat: add Contributors name automatically to README
  .github/workflows /Contributors.yml
  README.md
Labels: documentation, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#27 refactor: update bg and result wording
  assets/css/index.css
  assets/js/script.js
  index.html
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST
